/**
 *
 * SB_NC_ReservedTest
 *  予備のカスタム表示ラベルをパッケージにいれるため。。。
 *
 * Copyright (C) 2018 SunBridge Inc. All Rights Reserved.
 *
 *  @author sawano
 *  @Version 1      2018.09.xx
 *
 **/

@isTest
private class SB_NC_ReservedTest
{
  @isTest
  static void test_ReservedLabel()
  {
    System.assert(String.isNotBlank(Label.SB_NC_Reserved01));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved02));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved03));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved04));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved05));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved06));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved07));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved08));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved09));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved10));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved11));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved12));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved13));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved14));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved15));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved16));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved17));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved18));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved19));
    System.assert(String.isNotBlank(Label.SB_NC_Reserved20));
  }
}