/*
 * Copyright (c) 2014-2015 SunBridge Inc.
 *
 * 日経テレコン人事異動情報 WSI API
 *
 * 注意
 * http://www.salesforce.com/us/developer/docs/apexcode/Content/apex_gov_limits.htm
 * Total number of callouts (HTTP requests or Web services calls) in a transaction         10
 * Maximum timeout for all callouts (HTTP requests or Web services calls) in a transaction 120 seconds
 * Default timeout of callouts (HTTP requests or Web services calls) in a transaction      10 seconds
 * Maximum size of callout request or response (HTTP request or Web services call)         3 MB
 */

public class SB_NameCard_JinjiIdoApi {}