version: 2.1
orbs:
  sfdx: circleci/salesforce-sfdx@2.1.0
  slack: circleci/slack@3.4.2

####################################################################################################
## JOB:     build-and-test
## PURPOSE:
####################################################################################################
jobs:
  build-and-test:
    executor: sfdx/default
    working_directory: ~/smartvisca-package
    steps:
      - checkout
      # 20200915 ソースdeployエラーのため、CLI最新版に変更
      # - sfdx/install:
      #     version: "7.69.0"
      - sfdx/install
      #　DEV環境認証開始
      - run:
          name: create DEV org server key
          command : |
            if [ $CIRCLE_PULL_REQUEST ]; then
              openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K ${DECRYPTION_KEY} -iv ${DECRYPTION_IV}
            else
              exit 0
            fi
      - run: 
          name: DEV jwt
          command : | 
            if [ $CIRCLE_PULL_REQUEST ]; then
              sfdx force:auth:jwt:grant --clientid ${HUB_CONSUMER_KEY} --jwtkeyfile assets/server.key --username ${HUB_SFDC_USER} --setdefaultdevhubusername --setalias DEV-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}
            else
              exit 0
            fi
      #　DEV環境認証完了
      - run:
          name: Setup Org
          command: |
            if [ $CIRCLE_PULL_REQUEST ]; then
              echo 'Test scratch環境の作成 '
              sfdx force:limits:api:display -u DEV-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}
              sfdx force:org:create -f ~/smartvisca-package/config/project-scratch-def-developer.json -a circle_build_test -s -d 1 --wait 5
              sfdx force:source:deploy -u circle_build_test -p sfdx-source/SmartVisca
              sfdx force:source:deploy -u circle_build_test -p sfdx-source/unpackaged/dev-config
              sfdx force:user:create --setalias ${CIRCLE_WORKFLOW_ID}@test.org --definitionfile config/project-user-admin-def.json
              sfdx force:apex:execute -u ${CIRCLE_WORKFLOW_ID}@test.org -f script/apex/postinstall.apex
            else
              exit 0
            fi
      - run:
          name: Run Apex Tests
          no_output_timeout: 30m
          command: |
            if [ $CIRCLE_PULL_REQUEST ]; then
              echo 'Running Apex Tests'
              mkdir -p ~/junit
              sfdx force:apex:test:run -c -d ~/junit -r junit -u ${CIRCLE_WORKFLOW_ID}@test.org --wait 30
              echo 'export TESTMSG_HEAD=$(echo Unit Test が正常に完了しました。)' >> $BASH_ENV
              source $BASH_ENV
            else
              echo 'export TESTMSG_HEAD=$(echo PRを出していない場合、Unit Test が実行しません。)' >> $BASH_ENV
              source $BASH_ENV
              exit 0
            fi

      - store_test_results:
          path: ~/junit

      - run:
          name: Delete Useless Scratch Org
          command: |
            if [ $CIRCLE_PULL_REQUEST ]; then
              sfdx force:org:delete -u circle_build_test -p
            else
              exit 0
            fi

      - slack/notify:
          channel: ${SLACK_CHANNEL}
          color: '#42e2f4'
          message: "${TESTMSG_HEAD} \n 名前：$CIRCLE_USERNAME \n ブランチ：${CIRCLE_BRANCH}"
          webhook: '${SLACK_WEBHOOK}'
          include_job_number_field: false

      - slack/status:
          fail_only: true
          channel: ${SLACK_CHANNEL}
          webhook: '${SLACK_WEBHOOK}'
          failure_message: "名前：$CIRCLE_USERNAME \n ブランチ：$CIRCLE_BRANCH \n CIRCLE JOB が失敗しました。確認してください。"

####################################################################################################
## JOB:     create-feature-scratch
## PURPOSE:
####################################################################################################
  create-feature-scratch:
    executor: sfdx/default
    working_directory: ~/smartvisca-package
    steps:
      - checkout
      # 20200915 ソースdeployエラーのため、CLI最新版に変更
      # - sfdx/install:
      #     version: "7.69.0"
      - sfdx/install

      #　DEV環境認証開始
      - run: 
          name: create server key 
          command: openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K ${DECRYPTION_KEY} -iv ${DECRYPTION_IV}
      - run: 
          name: DEV jwt
          command: sfdx force:auth:jwt:grant --clientid ${HUB_CONSUMER_KEY} --jwtkeyfile assets/server.key --username ${HUB_SFDC_USER} --setdefaultdevhubusername --setalias DEV-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}
      #　DEV環境認証完了

      - run:
          name: create-feature-scratch
          command: |
            sfdx force:data:soql:query -q "SELECT Name,OrgName,ScratchOrg,Description FROM ScratchOrgInfo WHERE status = 'Active' AND OrgName = '$CIRCLE_BRANCH'" -u DEV-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH} | wc -l > scratchorg.cnt
            cat scratchorg.cnt
            SCRATCH_CNT=$(cat scratchorg.cnt)
            echo "scratch:count=${SCRATCH_CNT}"
            echo "'$CIRCLE_BRANCH'"
            echo "${CIRCLE_BRANCH}"
            if [ "${SCRATCH_CNT}" = "1" ]; then
              echo 'Featrue scratch環境の作成 '

              sfdx force:org:create -f config/project-scratch-def-developer.json orgName=${CIRCLE_BRANCH} -a ${CIRCLE_BRANCH} -s -d 30  --wait 10
              sfdx force:source:deploy -u ${CIRCLE_BRANCH} -p sfdx-source/SmartVisca
              sfdx force:source:deploy -u ${CIRCLE_BRANCH} -p sfdx-source/unpackaged/dev-config
              sfdx force:user:create --setalias ${CIRCLE_WORKFLOW_ID}@feature.org --definitionfile config/project-user-admin-def.json
              sfdx force:apex:execute -u ${CIRCLE_WORKFLOW_ID}@feature.org -f script/apex/postinstall.apex
              sfdx force:user:password:generate -u ${CIRCLE_WORKFLOW_ID}@feature.org
              sfdx force:user:display --targetusername ${CIRCLE_WORKFLOW_ID}@feature.org | sed '1,3d' > ./dev_userPassword.txt
              cat ./dev_userPassword.txt
              echo 'export VERY_IMPORTANT=$(cat ./dev_userPassword.txt)' >> $BASH_ENV
              source $BASH_ENV
            else
              echo 'すでに環境が作成されています。'

            fi

      - slack/notify:
          channel: ${SLACK_CHANNEL}
          color: '#42e2f4'
          message: "Featrue scratch環境を作成しました。 \n ブランチ：${CIRCLE_BRANCH} \n ${VERY_IMPORTANT}"
          webhook: '${SLACK_WEBHOOK}'
          include_job_number_field: false
      
      - slack/status:
          fail_only: true
          channel: ${SLACK_CHANNEL}
          webhook: '${SLACK_WEBHOOK}'
          failure_message: "名前：$CIRCLE_USERNAME \n ブランチ：$CIRCLE_BRANCH \n CIRCLE JOB が失敗しました。確認してください。"

####################################################################################################
## JOB:     create-beta-package
## PURPOSE:
####################################################################################################
  create-beta-package:
    executor: sfdx/default
    docker:
      - image: circleci/node:current-browsers
    environment:
      PACKAGE_VERSION_NAME : September 2020
      METADATA_PACKAGE_ID : 0332x000000kRZ9AAM
    steps:
      - checkout
      # 20200915 ソースdeployエラーのため、CLI最新版に変更
      # - sfdx/install:
      #     version: "7.69.0"
      - sfdx/install

      - run:
          name: create date files
          command: |
            TODAY=$(date +%u)
            # 今週の月曜日を取得
            if [ 1 -lt TODAY]; then
              echo $(date "+%s" --date "last monday") > ./monday.txt
            else
              echo $(date "+%s") > ./monday.txt
            fi
            # 最新のcommit日を取得
            echo $(git log -1 --date=format:"%s" --format="%ad") > ./commit_date.txt
            # betaパッケージパージョン名
            echo $(date '+%Y%m%d') > ./version_name.txt

      #　PJT環境認証開始
      - run: 
          name: create PKG org server key
          command: |
            if [ $(cat monday.txt) -lt $(cat commit_date.txt) ]; then
              openssl enc -nosalt -aes-256-cbc -d -in assets/server_pkg.key.enc -out assets/server_pkg.key -base64 -K ${DECRYPTION_KEY} -iv ${DECRYPTION_IV}
            else
              exit 0
            fi
      - run: 
          name: PKG jwt
          command: |
            if [ $(cat monday.txt) -lt $(cat commit_date.txt) ]; then
              sfdx force:auth:jwt:grant --clientid 3MVG97quAmFZJfVy26n1jTv2MQMTgLt7ZYsH3w3hD177DJFK5u_Xj6B19joV7jNxYAmJlpeENdi7Pkl5lhfbx --jwtkeyfile assets/server_pkg.key --username svtestpjt@sohobb.jp --setdefaultdevhubusername  --setalias PKG-${CIRCLE_PROJECT_REPONAME}-BETA
              sfdx force:auth:jwt:grant --clientid 3MVG9Gdzj3taRxuMpe34wmRPIREGETTrR7PcjjsA6VRaTmviq4cTRgIKcj9NvSHy4im2Pbqie9DSgklfLlozr --jwtkeyfile assets/server_pkg.key --username test-vt6ut8sucqjx@example.com --setdefaultdevhubusername  --setalias QA-${CIRCLE_PROJECT_REPONAME}-BETA -r https://test.salesforce.com
              sfdx force:org:display -u QA-${CIRCLE_PROJECT_REPONAME}-BETA --json > ./qa_UserPassword.json
              cat ./qa_UserPassword.json
              else
              exit 0
            fi
      #　PJT環境認証完了
      #　DEV環境認証開始
      - run: 
          name: create DEV org server key
          command: |
            if [ $(cat monday.txt) -lt $(cat commit_date.txt) ]; then
              openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K ${DECRYPTION_KEY} -iv ${DECRYPTION_IV}
            else
              exit 0
            fi
      - run: 
          name: DEV jwt
          command: |
            if [ $(cat monday.txt) -lt $(cat commit_date.txt) ]; then
              sfdx force:auth:jwt:grant --clientid ${HUB_CONSUMER_KEY} --jwtkeyfile assets/server.key --username ${HUB_SFDC_USER} --setdefaultdevhubusername --setalias DEV-${CIRCLE_PROJECT_REPONAME}-BETA
            else
              exit 0
            fi

      # 　DEV環境認証完了
      # - run:
      #     name: Convert SFDX source to MDAPI source
      #     command: |
      #       if [ $(cat monday.txt) -lt $(cat commit_date.txt) ]; then
      #         # パッケージ用にprefixつけたソースに上書き
      #         cp sfdx-source/packaged/main sfdx-source/SmartVisca/ -f -r

      #         sfdx force:source:convert -r "$PACKAGE_DIRECTORY" \
      #                                   -d "./mdapi-source/circle_build_$CIRCLE_BUILD_NUM" \
      #                                   -n "svTest" \
      #                                   --loglevel error
      #         # package.xmlにインストール後スクリプトの記載
      #         sed -i 's|</Package>|<postInstallClass>SB_NC_PostInstallScript</postInstallClass></Package>|' ./mdapi-source/circle_build_$CIRCLE_BUILD_NUM/package.xml
      #         cat ./mdapi-source/circle_build_$CIRCLE_BUILD_NUM/package.xml
      #       else
      #         exit 0
      #       fi

      # - run:
      #     name: Deploy MDAPI Source to the Packaging Org
      #     command: |
      #       if [ $(cat monday.txt) -lt $(cat commit_date.txt) ]; then
      #         sfdx force:mdapi:deploy -d "./mdapi-source/circle_build_$CIRCLE_BUILD_NUM" \
      #                                 -u PKG-${CIRCLE_PROJECT_REPONAME}-BETA \
      #                                 -w 15 \
      #                                 --verbose \
      #                                 --loglevel error
      #       else
      #         exit 0
      #       fi

      # - run:
      #     name: List current version history for the first-generation package about to be uploaded
      #     command: |
      #       if [ $(cat monday.txt) -lt $(cat commit_date.txt) ]; then
      #         sfdx force:package1:version:list -u PKG-${CIRCLE_PROJECT_REPONAME}-BETA \
      #                                          -i $METADATA_PACKAGE_ID \
      #                                          --loglevel error
      #       else
      #         exit 0
      #       fi

      # - run:
      #     name: Create (upload) a new MANAGED BETA package version
      #     no_output_timeout: 30m
      #     command: |
      #       if [ $(cat monday.txt) -lt $(cat commit_date.txt) ]; then
      #         sfdx force:package1:version:create -i $METADATA_PACKAGE_ID \
      #                                            -n "$PACKAGE_VERSION_NAME" \
      #                                            -d "Package version generated by CI process" \
      #                                            -u PKG-${CIRCLE_PROJECT_REPONAME}-BETA \
      #                                            -w 20 \
      #                                            --loglevel error > ./versionId.txt
      #         sfdx force:package1:version:list -u PKG-${CIRCLE_PROJECT_REPONAME}-BETA \
      #                                          -i $METADATA_PACKAGE_ID \
      #                                          --loglevel error > ./version_info.txt
      #         VID=$(cat ./versionId.txt)
      #         echo 'VID1 : ' ${VID}
      #         VID=`echo ${VID#*[}`
      #         echo 'VID2 : ' ${VID}
      #         VID=`echo ${VID%]*}`
      #         echo 'VID3 : ' ${VID}
      #         echo 'export VERSIONID_ENV=${VID}' >> $BASH_ENV
      #         source $BASH_ENV
      #         grep ${VERSIONID_ENV} ./version_info.txt > pkg_info.txt
      #         echo 'QA scratch環境の作成 '
      #         sfdx force:org:create -f config/project-scratch-def.json orgName=${CIRCLE_WORKFLOW_ID}-QA-${CIRCLE_PROJECT_REPONAME}-BETA -a QA-${CIRCLE_PROJECT_REPONAME}-BETA -n -s -d 30 --wait 10
      #         sfdx force:org:list --all
      #         sfdx force:package:install --package $VERSIONID_ENV -u QA-${CIRCLE_PROJECT_REPONAME}-BETA --publishwait 15 --wait 15
      #         sfdx force:user:password:generate -u QA-${CIRCLE_PROJECT_REPONAME}-BETA
      #         sfdx force:user:display --targetusername QA-${CIRCLE_PROJECT_REPONAME}-BETA --json > ./qa_UserPassword.json
      #         cat ./qa_UserPassword.json
      #         echo 'export QAVERY_IMPORTANT=$(cat ./qa_UserPassword.json)' >> $BASH_ENV
      #         echo 'export QAMSG_HEAD=$(echo ベターパッケージ QA scratch環境を作成しました。)' >> $BASH_ENV
      #         source $BASH_ENV
      #       else
      #         exit 0
      #       fi

      # - run:
      #     name: create and push beta tag
      #     command: |
      #       if [ $(cat monday.txt) -lt $(cat commit_date.txt) ]; then
      #         # betaタグを作成　例：beta_1.0.0_20200819
      #         PKG_INFO=$(cat pkg_info.txt)
      #         if [[ $PKG_INFO =~ [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]]; then
      #           PKG_VERSION=${BASH_REMATCH[0]}
      #         fi
      #         TAG_HEAD=$(echo beta_)
      #         UB=$(echo _)
      #         VERSION_NAME=$(cat version_name.txt)
      #         BETA_TAG=$(echo $TAG_HEAD$PKG_VERSION$UB${VERSION_NAME})2
      #         echo '{"betatag":"'$BETA_TAG'"}' > data/beta_tag.json
      #         git tag $BETA_TAG
      #         git push origin $BETA_TAG
      #       else
      #         exit 0
      #       fi

      - run:
          name: initial setting in  SmartVisca-package
          command: |
            if [ $(cat monday.txt) -lt $(cat commit_date.txt) ]; then
              # sfdx force:org:list --all
              # # 環境設定
              # sfdx force:source:deploy -u QA-${CIRCLE_PROJECT_REPONAME}-BETA -p sfdx-source/unpackaged/qa-config
              # sfdx force:apex:execute -u  QA-${CIRCLE_PROJECT_REPONAME}-BETA -f script/apex/SB_AutomaticcCooperationSetting.apex

              # sfdx force:user:permset:assign --permsetname "permset" --targetusername QA-${CIRCLE_PROJECT_REPONAME}-BETA
              # sfdx force:user:permset:assign --permsetname "SmartViscaAdminUser" --targetusername QA-${CIRCLE_PROJECT_REPONAME}-BETA

              # sfdx force:user:create --setalias test2-${CIRCLE_WORKFLOW_ID}@package.org --definitionfile data/test-users/svdemo_mktg2019.xltvyt2mceva.uo598j4fqxu8@sv.com.json username=svdemo_mktg${CIRCLE_WORKFLOW_ID}@sv.com -u QA-${CIRCLE_PROJECT_REPONAME}-BETA
              # sfdx force:user:create --setalias test3-${CIRCLE_WORKFLOW_ID}@package.org --definitionfile data/test-users/svdemo_sales2019.qmwtyalmpjol.o9x6vrua3tos@sv.com.json username=svdemo_sales${CIRCLE_WORKFLOW_ID}@sv.com -u QA-${CIRCLE_PROJECT_REPONAME}-BETA
              # sfdx force:user:create --setalias test4-${CIRCLE_WORKFLOW_ID}@package.org --definitionfile data/test-users/svdemo_salesmgr2019.shqp9lpwtmwl.n4al68ywrcoq@sv.com.json username=svdemo_salesmgr${CIRCLE_WORKFLOW_ID}@sv.com -u QA-${CIRCLE_PROJECT_REPONAME}-BETA
              # sfdx force:data:tree:import -p data/test-records/SmartViscaf__NameCard__c-Account-Contact-plan.json -u  QA-${CIRCLE_PROJECT_REPONAME}-BETA
              # sfdx force:apex:execute -u  QA-${CIRCLE_PROJECT_REPONAME}-BETA -f script/apex/updateNameCardReferAttachment.apex

              npm install
              npx mocha script/e2e/SmartViscaInitialSetting.js --timeout 0

            else
              exit 0
            fi

      - slack/notify:
          channel: ${SLACK_CHANNEL}
          color: '#42e2f4'
          message: "${QAMSG_HEAD} \n タグ：$BETA_TAG \n ${QAVERY_IMPORTANT}"
          webhook: '${SLACK_WEBHOOK}'
          include_job_number_field: false

      - slack/status:
          fail_only: true
          channel: ${SLACK_CHANNEL}
          webhook: '${SLACK_WEBHOOK}'
          failure_message: "名前：$CIRCLE_USERNAME \n タグ：$CIRCLE_TAG \n CIRCLE JOB が失敗しました。確認してください。"

workflows:
  version: 2.1
  commit-workflow:
    jobs:
      - create-beta-package