version: 2.1
orbs:
  sfdx: circleci/salesforce-sfdx@2.1.0
  slack: circleci/slack@3.4.2

####################################################################################################
## JOB:     build-and-test
## PURPOSE:
####################################################################################################
jobs:
  build-and-test:
    executor: sfdx/default
    working_directory: ~/sfdx-circleci

    steps:
      - checkout
      # 20200915 ソースdeployエラーのため、CLI最新版に変更
      # - sfdx/install:
      #     version: "7.69.0"
      - sfdx/install
      - run:
          name: create server key
          command : |
              echo `date`

workflows:
  version: 2.1
  scheduled-preproduction-workflow:
    triggers:
      - schedule:
          cron: "2 8 * * *"
    jobs:
      - build-and-test
          
  scheduled-develop-workflow:
    triggers:
      - schedule:
          cron: "5 8 * * *"
    jobs:
      - build-and-test


