version: 2.1
orbs:
  sfdx: circleci/salesforce-sfdx@2.0.0
  slack: circleci/slack@3.4.2

general:
# Uncomment the following to specify only a specific branch
#   branches:
#     only:
#       - dev # specific branch
#       - /dev-.*/ # or regexes

jobs:
  build:
    executor: sfdx/default
    # environment:
    #   RES: res
    steps:
      - checkout
      - sfdx/install
      # - run: echo $SFDX_JWT_KEY | base64 --decode --ignore-garbage > ./server.key
      # - run: sfdx force:auth:jwt:grant --clientid ${SFDX_CONSUMER_KEY} --jwtkeyfile assets/server.key --username ${HUB_SFDC_USER} --setdefaultdevhubusername --setalias ${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}
      # - run: openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K ${DECRYPTION_KEY} -iv ${DECRYPTION_IV}
      # - run: sfdx force:auth:jwt:grant --clientid ${SFDX_CONSUMER_KEY} --jwtkeyfile assets/server.key --username ${HUB_SFDC_USER} --setdefaultdevhubusername --setalias ${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}


####################################################################################################
## JOB:     create-dev-scratch-org
## PURPOSE:
####################################################################################################
  create-dev-scratch-org:
    docker:
      - image: ncino/ci-sfdx
    # machine: true
    working_directory: ~/ci_app
    steps:
      - checkout
      - run:
          name: create-feature-scratch
          command: |
            echo 'create-feature-scratch'
            openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K ${DECRYPTION_KEY} -iv ${DECRYPTION_IV}
            sfdx force:auth:jwt:grant --clientid ${SFDX_CONSUMER_KEY} --jwtkeyfile assets/server.key --username ${HUB_SFDC_USER} --setdefaultdevhubusername --setalias ${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}

            sfdx force:org:create username=${CIRCLE_WORKFLOW_ID}@test.org -f config/project-scratch-def.json -a ${CIRCLE_BRANCH} -s -d 30 --wait 5 
      - run:
         name: 実行時の PATH 書き換えおよび環境変数定義
         command: |
          sfdx force:user:password:generate -u ${CIRCLE_WORKFLOW_ID}@test.org >> /tmp/ss.txt
      - run:
         name: 実行時の PATH 書き換えおよび環境変数定義
         command: |
          sfdx force:org:list >> /tmp/ss.txt
      - run: |
          echo 'export VERY_IMPORTANT=$(cat /tmp/ss.txt)' >> $BASH_ENV
          source $BASH_ENV



workflows:
  version: 2.1
  create_dev_scratch_org:
    jobs:
      - build:
        filters:
              branches:
                only:
                  - /feature.*/
                ignore:
                  - master
                  - PreProduction
                  - Production
      - create-dev-scratch-org:
          requires:
            - build

          
  # build_and_test:
  #   jobs:
  #     - build
          # context: org-sbdevhub
          # filters:
          #   branches:
          #     only:
          #       - master
  # create_beta_package:
  #   jobs:
  #     - create-beta-package:
  #         context: org-sbdevhub
  #         filters:  # ブランチのない、「v」から始まるタグに対してのみ実行します。
  #           tags:
  #              only:
  #                - /v.*/
  #           branches:
  #             ignore: /.*/

      # - slack/notify:
      #     channel: '#general'
      #     color: '#42e2f4'
      #     include_job_number_field: false
      #     message: 'testbranch'
      #     webhook: '${SLACK_WEBHOOK}'