/**
 *
 * SB_NCL_ReservedTest
 *  予備のカスタム表示ラベルをパッケージにいれるため。。。
 *
 * Copyright (C) 2018 SunBridge Inc. All Rights Reserved.
 *
 *  @author sawano
 *  @Version 1      2018.09.xx
 *
 **/

@isTest
private class SB_NCL_ReservedTest
{
  @isTest
  static void test_ReservedLabel()
  {
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved01));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved02));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved03));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved04));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved05));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved06));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved07));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved08));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved09));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved10));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved11));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved12));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved13));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved14));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved15));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved16));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved17));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved18));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved19));
    System.assert(String.isNotBlank(Label.SB_NCL_Reserved20));
  }
}